public enum TileType
{
    None,
    Grass,
    GrassOvergrown,
    EncounterGrass,
    Path,
    Building_Roof,
    Building_Wall,
    Building_Window,
    Building_Door,
    Interior_Floor,
    Interior_Bed,
    Interior_Dresser,
    Interior_Wall,
    Interior_Stool,
    Interior_Table,
    Interior_Doormat,
    Interior_Door,
    Interior_Cabinet,
    Interior_Sink,
    Interior_Oven,
    Interior_Fridge
}